# Generated by Django 5.0.4 on 2026-05-20 16:22

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom (FR)')),
                ('name_en', models.CharField(blank=True, default='', max_length=255, verbose_name='Nom (EN)')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('bio_fr', models.TextField(blank=True, default='', verbose_name='Biographie (FR)')),
                ('bio_en', models.TextField(blank=True, default='', verbose_name='Biographie (EN)')),
                ('bio_ar', models.TextField(blank=True, default='', verbose_name='Biographie (AR)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=api.models.author_photo_path, verbose_name='Photo')),
                ('country', models.CharField(blank=True, default='', max_length=100, verbose_name='Pays')),
                ('is_author_of_month', models.BooleanField(default=False, verbose_name='Auteur du mois')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Auteur',
                'verbose_name_plural': 'Auteurs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Titre (FR)')),
                ('title_en', models.CharField(blank=True, default='', max_length=500, verbose_name='Titre (EN)')),
                ('title_ar', models.CharField(blank=True, default='', max_length=500, verbose_name='Titre (AR)')),
                ('slug', models.SlugField(blank=True, max_length=500, unique=True)),
                ('content_fr', models.TextField(blank=True, default='', verbose_name='Contenu (FR)')),
                ('content_en', models.TextField(blank=True, default='', verbose_name='Contenu (EN)')),
                ('content_ar', models.TextField(blank=True, default='', verbose_name='Contenu (AR)')),
                ('image', models.ImageField(blank=True, null=True, upload_to=api.models.news_image_path, verbose_name='Image')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('author', models.CharField(blank=True, default='', max_length=255, verbose_name='Auteur (texte libre)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name="Titre de l'article")),
                ('media_name', models.CharField(max_length=255, verbose_name='Nom du média')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='Date de publication')),
                ('excerpt', models.TextField(blank=True, default='', verbose_name='Extrait')),
                ('article_url', models.URLField(blank=True, default='', verbose_name="URL de l'article")),
                ('logo', models.ImageField(blank=True, null=True, upload_to=api.models.press_logo_path, verbose_name='Logo du média')),
                ('featured', models.BooleanField(default=False, verbose_name='À la une')),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to=api.models.press_file_path, verbose_name='Fichier joint')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Article de presse',
                'verbose_name_plural': 'Articles de presse',
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Titre (FR)')),
                ('title_en', models.CharField(blank=True, default='', max_length=500, verbose_name='Titre (EN)')),
                ('title_ar', models.CharField(blank=True, default='', max_length=500, verbose_name='Titre (AR)')),
                ('slug', models.SlugField(blank=True, max_length=500, unique=True)),
                ('author_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Nom auteur (libre)')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description (FR)')),
                ('description_en', models.TextField(blank=True, default='', verbose_name='Description (EN)')),
                ('description_ar', models.TextField(blank=True, default='', verbose_name='Description (AR)')),
                ('cover', models.ImageField(blank=True, null=True, upload_to=api.models.book_cover_path, verbose_name='Couverture')),
                ('price_dt', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix (DT)')),
                ('price_eur', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix (EUR)')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Année')),
                ('pages', models.IntegerField(blank=True, null=True, verbose_name='Pages')),
                ('isbn', models.CharField(blank=True, default='', max_length=50, verbose_name='ISBN')),
                ('language', models.CharField(blank=True, choices=[('fr', 'Français'), ('ar', 'Arabe'), ('en', 'Anglais'), ('bi', 'Bilingue')], default='fr', max_length=10, verbose_name='Langue')),
                ('category', models.CharField(blank=True, default='', max_length=100, verbose_name='Catégorie')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='api.author', verbose_name='Auteur')),
            ],
            options={
                'verbose_name': 'Livre',
                'verbose_name_plural': 'Livres',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=500, verbose_name='Titre (FR)')),
                ('title_en', models.CharField(blank=True, default='', max_length=500, verbose_name='Titre (EN)')),
                ('title_ar', models.CharField(blank=True, default='', max_length=500, verbose_name='Titre (AR)')),
                ('subtitle', models.CharField(blank=True, default='', max_length=500, verbose_name='Sous-titre (FR)')),
                ('subtitle_en', models.CharField(blank=True, default='', max_length=500, verbose_name='Sous-titre (EN)')),
                ('subtitle_ar', models.CharField(blank=True, default='', max_length=500, verbose_name='Sous-titre (AR)')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description (FR)')),
                ('description_en', models.TextField(blank=True, default='', verbose_name='Description (EN)')),
                ('description_ar', models.TextField(blank=True, default='', verbose_name='Description (AR)')),
                ('cta_label', models.CharField(blank=True, default='', max_length=200, verbose_name='Bouton (FR)')),
                ('cta_label_en', models.CharField(blank=True, default='', max_length=200, verbose_name='Bouton (EN)')),
                ('cta_label_ar', models.CharField(blank=True, default='', max_length=200, verbose_name='Bouton (AR)')),
                ('cta_url', models.CharField(blank=True, default='', max_length=500, verbose_name='URL du bouton')),
                ('image', models.ImageField(blank=True, null=True, upload_to=api.models.hero_image_path, verbose_name='Image')),
                ('type', models.CharField(choices=[('main', 'Principal'), ('secondary', 'Secondaire'), ('author', 'Auteur du mois'), ('promo', 'Promotion')], default='main', max_length=50, verbose_name='Type')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_of_month', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_sections', to='api.author', verbose_name='Auteur du mois lié')),
            ],
            options={
                'verbose_name': 'Section Hero',
                'verbose_name_plural': 'Sections Hero',
                'ordering': ['order'],
            },
        ),
    ]
