# Generated by Django 5.0.4 on 2026-05-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='type',
            field=models.CharField(choices=[('main', 'Principal'), ('secondary', 'Secondaire'), ('author', 'Auteur du mois'), ('promo', 'Promotion'), ('latest', 'Dernières parutions'), ('news', 'Actualités')], default='main', max_length=50, verbose_name='Type'),
        ),
    ]
